language: python
python:
  - "2.7"
script: nosetests
env:
  - DJANGO=django==1.4.8
  - DJANGO=django==1.5.4
  - DJANGO=https://www.djangoproject.com/download/1.6b4/tarball/

install:
  - pip install -q $DJANGO
  - python setup.py -q install
  - pip install -r requirements/install.pip --use-mirrors
  - pip install -r requirements/testing.pip --use-mirrors

script: django-admin.py test geo --settings=geo.test_settings
