language: python
python:
  - "2.7"

env:
  - DJANGO=1.4.x
  - DJANGO=1.5.x
  - DJANGO=1.6.x
  - DJANGO=dev

install:
  - pip install -q $DJANGO
  - python setup.py -q install
  - pip install -r geo/requirements/install.pip --use-mirrors
  - pip install -r geo/requirements/testing.pip --use-mirrors

script: django-admin.py test geo --settings=geo.tests.settings
