language: python
python:
  - "2.7"

env:
  - DJANGO=1.4.x
  - DJANGO=1.5.x
  - DJANGO=1.6.x
  - DJANGO=dev

script:
  - python setup.py -q install
  - pip unistall django-geo
  - make test


after_success:
  - coveralls
