language: python
python:
  - "2.7"
script: nosetests
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r requirements.txt --use-mirrors

script: django-admin.py test geo --settings=geo.test_settings
